import { useState } from "react";
import { Link } from "wouter";
import { Btn, Card, ErrorLine, Loading, NeedPassport, PageHead, Stat } from "../components/bits";
import { useSession } from "../components/session";
import { useCureNotice, useForeclose, useHouseLedger, useHouseNotices, useIssueDefault, useIssueGrace, useWatchlist } from "../queries/house";
import { useEscrowQueue, useEscrowReview } from "../queries/payouts";
import { date, money } from "../lib/format";

export default function HousePage() { return <NeedPassport><House /></NeedPassport>; }
function House() {
  const { memberId, member } = useSession(); const admin = member?.role === "admin";
  const ledger = useHouseLedger(memberId, admin); const watch = useWatchlist(memberId, admin); const notices = useHouseNotices(memberId, admin); const queue = useEscrowQueue(memberId, admin);
  const grace = useIssueGrace(); const def = useIssueDefault(); const cure = useCureNotice(); const foreclose = useForeclose(); const review = useEscrowReview();
  const [notes, setNotes] = useState<Record<string, string>>({}); const [confirm, setConfirm] = useState<number | null>(null);
  const note = (key: string) => <textarea className="k-input mt-3" aria-label="Review or recovery note" placeholder="Written reason or recovery plan (5+ characters)" minLength={5} maxLength={600} value={notes[key] ?? ""} onChange={(e) => setNotes({ ...notes, [key]: e.target.value })} />;
  if (!admin) return <Card><h1 className="k-display text-3xl">House desk is admin-only</h1><p className="mt-3 text-muted-foreground">Use the house demo passport on the <Link className="k-link" to="/join">Passport page</Link>. This is a demo gate, not production authentication.</p></Card>;
  return <div><PageHead kicker="House · Simulated operations" title="The open books">10% house take. A quarter of that fee to the Reserve. Accommodation before enforcement. These are demo operations, not licensed custody.</PageHead>
    {ledger.isLoading ? <Loading /> : <div className="grid gap-4 md:grid-cols-4"><Stat label="House (sim)" value={money(ledger.data?.houseCents)} /><Stat label="Reserve" value={money(ledger.data?.reserveCents)} /><Stat label="Feature fund" value={money(ledger.data?.featureFundCents)} /><Stat label="Escrow ledger" value={money(ledger.data?.escrowHeldCents)} /></div>}
    <h2 className="k-display mt-10 text-3xl">Escrow review</h2>
    {queue.isLoading ? <Loading /> : <div className="mt-4 space-y-4">{!queue.data?.length && <p className="text-sm text-muted-foreground">No evidence awaiting review.</p>}{queue.data?.map((m) => <Card key={m.id}><div className="k-label">{m.projectTitle} · Stage {m.stage}</div><h3 className="mt-2 font-semibold">{m.title}</h3><p className="mt-2 whitespace-pre-wrap text-sm">{m.evidence}</p><p className="mt-2 text-xs text-muted-foreground">{m.escrowVendor} · {money(m.raisedCents)} raised</p>{note(`m${m.id}`)}<div className="mt-3 flex gap-2"><Btn disabled={(notes[`m${m.id}`]?.trim().length ?? 0) < 5} loading={review.isPending} onClick={() => memberId && review.mutate({ memberId, milestoneId: m.id, approve: true, note: notes[`m${m.id}`] })}>Approve & release</Btn><Btn variant="outline" disabled={(notes[`m${m.id}`]?.trim().length ?? 0) < 5} loading={review.isPending} onClick={() => memberId && review.mutate({ memberId, milestoneId: m.id, approve: false, note: notes[`m${m.id}`] })}>Return for revision</Btn></div></Card>)}</div>}
    <ErrorLine error={queue.error ?? review.error} />{review.data && <output className="mt-3 text-good">{review.data.approved ? `Approved. ${money(review.data.releasedCents)} released; stage ${review.data.stage}.` : "Returned with a cure path. No penalty."}</output>}
    <h2 className="k-display mt-10 text-3xl">Accommodation ladder</h2><p className="mt-2 text-sm text-muted-foreground">Grace → expired grace → default notice → expired cure window → foreclosure. Difficulty is not a default.</p>
    {watch.isLoading ? <Loading /> : <div className="mt-4 space-y-4">{watch.data?.map((p) => {
      const reason = notes[`p${p.id}`] ?? ""; const valid = reason.trim().length >= 5; const expired = !!p.graceUntil && new Date(p.graceUntil).getTime() < Date.now();
      return <Card key={p.id}><div className="flex flex-wrap justify-between gap-3"><Link className="k-link font-semibold" to={`/forge/project/${p.id}`}>{p.title}</Link><span className="k-chip">{p.idleDays} idle days · {p.escalation}</span></div><p className="mt-2 text-sm text-muted-foreground">{p.recommendation}</p>{p.graceUntil && <p className="mt-2 text-xs">Window closes {date(p.graceUntil)}</p>}{note(`p${p.id}`)}<div className="mt-3 flex flex-wrap gap-2"><Btn variant="outline" disabled={!valid || p.status === "default_notice"} loading={grace.isPending} onClick={() => memberId && grace.mutate({ memberId, projectId: p.id, reason })}>Open grace</Btn><Btn variant="outline" disabled={!valid || !expired || p.status === "default_notice"} loading={def.isPending} onClick={() => memberId && def.mutate({ memberId, projectId: p.id, reason })}>Default notice</Btn><Btn variant="danger" disabled={!valid || p.status !== "default_notice" || !expired} loading={foreclose.isPending} onClick={() => setConfirm(p.id)}>Foreclose…</Btn></div>{confirm === p.id && <div className="mt-4 border border-destructive p-4"><p className="text-sm">Redistribute this project's residual escrow and list creator equity? This cannot be undone in the demo.</p><div className="mt-3 flex gap-2"><Btn variant="danger" loading={foreclose.isPending} onClick={() => memberId && foreclose.mutate({ memberId, projectId: p.id, reason }, { onSuccess: () => setConfirm(null) })}>Confirm redistribution</Btn><Btn variant="outline" onClick={() => setConfirm(null)}>Keep project</Btn></div></div>}</Card>;
    })}</div>}
    <ErrorLine error={watch.error ?? grace.error ?? def.error ?? foreclose.error} />
    <h2 className="k-display mt-10 text-3xl">Open notices</h2>
    {notices.isLoading ? <Loading /> : <div className="mt-4 space-y-4">{notices.data?.map((n) => <Card key={n.id}><div className="k-label">@{n.handle} · {n.kind}</div><h3 className="mt-2 font-semibold">{n.title}</h3><p className="mt-2 whitespace-pre-wrap text-sm text-muted-foreground">{n.body}</p><p className="mt-2 text-sm"><b>Recovery:</b> {n.recoveryPath}</p>{["grace", "default_notice", "cure_plan"].includes(n.kind) && <>{note(`n${n.id}`)}<Btn className="mt-3" disabled={(notes[`n${n.id}`]?.trim().length ?? 0) < 5} loading={cure.isPending} onClick={() => memberId && cure.mutate({ memberId, noticeId: n.id, resolution: notes[`n${n.id}`] })}>Resolve & reinstate</Btn></>}</Card>)}</div>}
    <ErrorLine error={notices.error ?? cure.error} />
    <Card className="mt-10"><div className="flex justify-between gap-3"><h2 className="k-display text-3xl">Recent ledger</h2><Link to="/hub" className="k-link text-sm">Feature tallies →</Link></div><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr><th className="p-2">Date</th><th>Bucket</th><th>Kind</th><th>Amount</th><th>Note</th></tr></thead><tbody>{ledger.data?.recent.map((r) => <tr key={r.id} className="border-t border-border"><td className="p-2 whitespace-nowrap">{date(r.createdAt)}</td><td>{r.bucket}</td><td>{r.kind}</td><td className="whitespace-nowrap">{money(r.amountCents)}</td><td className="p-2 min-w-56">{r.note}</td></tr>)}</tbody></table></div><ErrorLine error={ledger.error} /></Card>
  </div>;
}