import { useState } from "react";
import { Btn, Card, ErrorLine, Field, Loading, PageHead, Stat } from "../components/bits";
import { useSession } from "../components/session";
import { useClaimTask, useMyTasks, useProposals, usePropose, useReserve, useSubmitTask, useTaskBoard, useVote } from "../queries/clout";
import { useFeatures, useVoteFeature } from "../queries/house";
import { money, ratio } from "../lib/format";

export default function HubPage() {
  const { memberId, member } = useSession();
  const reserve = useReserve(); const board = useTaskBoard(); const tasks = useMyTasks(memberId);
  const proposals = useProposals(); const features = useFeatures();
  const claim = useClaimTask(); const submit = useSubmitTask(); const propose = usePropose(); const vote = useVote(); const featureVote = useVoteFeature();
  const [proof, setProof] = useState<Record<number, string>>({}); const [title, setTitle] = useState(""); const [body, setBody] = useState("");
  return <div><PageHead kicker="Kinship Hub · Trust layer" title="Build the commons">The Hub holds only the Mutual Cover Reserve. It does not hold project capital. Contribution earns influence; it doesn't buy certainty.</PageHead>
    {reserve.isLoading ? <Loading /> : <><div className="grid gap-4 md:grid-cols-3"><Stat label="Reserve (sim)" value={money(reserve.data?.reserveCents)} /><Stat label="Escrow exposure (sim)" value={money(reserve.data?.exposureCents)} /><Stat label="Coverage · not a guarantee" value={ratio(reserve.data?.coverageRatio)} sub="25% target" /></div><Card className="mt-4"><p className="text-sm">{reserve.data?.honest}</p><ul className="mt-4 list-disc space-y-2 pl-5 text-xs text-muted-foreground">{reserve.data?.mechanics.map((m) => <li key={m}>{m}</li>)}</ul></Card></>}
    <ErrorLine error={reserve.error} />
    <h2 className="k-display mt-10 text-3xl">Do useful work</h2><p className="mt-2 text-sm text-muted-foreground">Rewards are auto-approved in this demo. Production requires peer review; truthful evidence only.</p>
    {board.isLoading ? <Loading /> : <div className="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{board.data?.map((t) => <Card key={t.kind}><h3 className="font-semibold">{t.title}</h3><p className="my-3 text-sm text-muted-foreground">{t.detail}</p><div className="mb-3 k-num text-xs">{t.points} points · {t.clout} clout</div><Btn disabled={!memberId} loading={claim.isPending} onClick={() => memberId && claim.mutate({ memberId, kind: t.kind, title: t.title })}>Claim task</Btn></Card>)}</div>}
    <ErrorLine error={board.error ?? claim.error} />
    {tasks.isLoading ? <Loading /> : <div className="mt-4 space-y-3">{tasks.data?.map((t) => <Card key={t.id}><div className="flex justify-between gap-4"><b>{t.title}</b><span className="k-chip">{t.status}</span></div>{t.status === "claimed" && <form className="mt-3 flex flex-wrap gap-3" onSubmit={(e) => { e.preventDefault(); if (memberId) submit.mutate({ memberId, taskId: t.id, proof: proof[t.id] ?? "" }); }}><input className="k-input flex-1" aria-label={`Evidence for ${t.title}`} required minLength={10} maxLength={2000} placeholder="Evidence link or explanation (10+ characters)" value={proof[t.id] ?? ""} onChange={(e) => setProof({ ...proof, [t.id]: e.target.value })} /><Btn loading={submit.isPending}>Submit evidence</Btn></form>}</Card>)}</div>}
    <ErrorLine error={tasks.error ?? submit.error} />
    <div className="mt-10 grid gap-6 lg:grid-cols-2"><section><h2 className="k-display mb-4 text-3xl">Member governance</h2><p className="mb-4 text-sm text-muted-foreground">Weight is 1 + floor(√clout). One vote per proposal.</p>{proposals.isLoading ? <Loading /> : <div className="space-y-4">{proposals.data?.map((p) => <Card key={p.id}><h3 className="font-semibold">{p.title}</h3><p className="my-3 whitespace-pre-wrap text-sm text-muted-foreground">{p.body}</p><p className="mb-3 k-num text-xs">Yes {p.yesWeight} · No {p.noWeight} · {p.status}</p><div className="flex gap-2">{(["yes", "no"] as const).map((choice) => <Btn key={choice} variant="outline" disabled={!memberId || p.status !== "open" || (p.closesAt ? new Date(p.closesAt).getTime() : 0) < Date.now()} loading={vote.isPending} onClick={() => memberId && vote.mutate({ memberId, proposalId: p.id, choice })}>{choice}</Btn>)}</div></Card>)}</div>}<ErrorLine error={proposals.error ?? vote.error} />
      <Card className="mt-4"><form className="space-y-3" onSubmit={(e) => { e.preventDefault(); if (memberId) propose.mutate({ memberId, title, body }, { onSuccess: () => { setTitle(""); setBody(""); } }); }}><div className="k-label">Propose · Level 1+</div><Field label="Title"><input className="k-input" required minLength={6} maxLength={140} aria-label="Proposal title" value={title} onChange={(e) => setTitle(e.target.value)} /></Field><Field label="Proposal"><textarea className="k-input min-h-28" required minLength={40} maxLength={4000} aria-label="Proposal body" value={body} onChange={(e) => setBody(e.target.value)} /></Field><Btn disabled={!memberId || (member?.level ?? 0) < 1} loading={propose.isPending}>Publish proposal</Btn><ErrorLine error={propose.error} /></form></Card></section>
      <section><h2 className="k-display mb-4 text-3xl">Failure into features</h2><p className="mb-4 text-sm text-muted-foreground">Foreclosed value funds member features, not house bonuses. One vote per member per feature.</p><Stat label="Feature fund (sim)" value={money(features.data?.fundCents)} />{features.isLoading ? <Loading /> : <div className="mt-4 space-y-4">{features.data?.features.map((f) => <Card key={f.id}><h3 className="font-semibold">{f.title}</h3><p className="my-3 text-sm text-muted-foreground">{f.description}</p><p className="mb-3 text-xs">{f.votes} votes · {f.status} · {money(f.targetCents)}</p><Btn disabled={!memberId} loading={featureVote.isPending} onClick={() => memberId && featureVote.mutate({ memberId, featureId: f.id })}>Vote for this</Btn></Card>)}</div>}<ErrorLine error={features.error ?? featureVote.error} />{featureVote.isSuccess && <output className="mt-3 text-sm text-good">Vote recorded.</output>}</section></div>
  </div>;
}